"""empty message

Revision ID: 143476e636b8
Revises: bb906ab88d12
Create Date: 2025-05-01 14:23:02.028811

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "143476e636b8"
down_revision: Union[str, None] = "bb906ab88d12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("player_1_id", sa.BigInteger(), nullable=False),
        sa.Column("player_2_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "FINISHED", "CANCELLED", name="gamestatus"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum("PLAYER1_WIN", "PLAYER2_WIN", "DRAW", "ABANDONED", name="gameresult"),
            nullable=True,
        ),
        sa.Column("is_bot_opponent", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["player_1_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_2_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    # ### end Alembic commands ###
